import type { components } from "./openapi"; // generated by openapi-typescript

export type Music = components["schemas"]["RichMusic"];

export type Album = components["schemas"]["RichAlbum"];

export type Artist = components["schemas"]["RichArtist"];

export type Id = components["schemas"]["Id"];

export type PlayerState = components["schemas"]["RichPlayerState"];

export type SearchQuery = components["schemas"]["SearchQuery"];

export type SearchResult = components["schemas"]["SearchResult"];

export type FetcherMusic = components["schemas"]["FetcherMusic"];
