import type { paths, components } from "./openapi"; // generated by openapi-typescript

export type Music = components["schemas"]["RichMusic"];

export type Album = components["schemas"]["RichAlbum"];

export type Artist = components["schemas"]["RichMusic"];
